version: '3.8'

services:
  airavata-monolithic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airavata-monolithic
    ports:
      - "8930:8930"  # Airavata API (Thrift RPC)
      - "8050:8050"  # File Server (Thrift RPC)
      - "18800:18800"  # Agent Service (Thrift RPC)
      - "18889:18889"  # Research Service (Thrift RPC)
      - "19900:19900"  # Agent Service gRPC
      - "19908:19908"  # Research Service gRPC
    volumes:
      # Mount your custom properties file here
      # Copy airavata-server.properties.example to airavata-server.properties and modify as needed
      - ./airavata-server.properties:/opt/airavata/vault/airavata-server.properties:ro
      - airavata-logs:/opt/airavata/logs
    environment:
      - JAVA_OPTS=-Xmx2g -Xms1g
    # All service logs (API, Pre-WM, Post-WM, etc.) will be captured by docker logs
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    depends_on:
      - mysql
      - rabbitmq
      - zookeeper
      - kafka
    networks:
      - airavata-network

  mysql:
    image: mariadb:10.11
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: airavata
      MYSQL_USER: airavata
      MYSQL_PASSWORD: airavata_password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - airavata-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: airavata-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: airavata
      RABBITMQ_DEFAULT_PASS: airavata
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks:
      - airavata-network

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: airavata-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-logs:/var/lib/zookeeper/log
    networks:
      - airavata-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: airavata-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    networks:
      - airavata-network

volumes:
  mysql-data:
  rabbitmq-data:
  zookeeper-data:
  zookeeper-logs:
  kafka-data:
  airavata-logs:

networks:
  airavata-network:
    driver: bridge 